map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/nginx/certs/t5c-local.crt;
    ssl_certificate_key /etc/nginx/certs/t5c-local.key;

    return 444;
}

server {
    listen 443 ssl;
    http2 on;
    server_name ${APP_DOMAIN};

    ssl_certificate /etc/nginx/certs/t5c-local.crt;
    ssl_certificate_key /etc/nginx/certs/t5c-local.key;

    resolver 127.0.0.11 valid=30s ipv6=off;
    set $t5c_server http://server:3000;

    location / {
        proxy_pass $t5c_server;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name ${GRAFANA_DOMAIN};

    ssl_certificate /etc/nginx/certs/t5c-local.crt;
    ssl_certificate_key /etc/nginx/certs/t5c-local.key;

    resolver 127.0.0.11 valid=30s ipv6=off;
    set $grafana http://grafana:3001;

    location / {
        proxy_pass $grafana;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name ${PROMETHEUS_DOMAIN};

    ssl_certificate /etc/nginx/certs/t5c-local.crt;
    ssl_certificate_key /etc/nginx/certs/t5c-local.key;

    resolver 127.0.0.11 valid=30s ipv6=off;
    set $prometheus http://prometheus:9090;

    location / {
        proxy_pass $prometheus;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
